package proyecto;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Daniel
 */
public class MantUsuario extends javax.swing.JFrame {

    /**
     * Creates new form MantUsuario
     */
    public MantUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NivelesdeAcceso = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SaveNombre = new javax.swing.JTextField();
        SaveLastName = new javax.swing.JTextField();
        SaveEmail = new javax.swing.JTextField();
        GuardarUsu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Salida = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Estado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Acceso1 = new javax.swing.JRadioButton();
        Acceso0 = new javax.swing.JRadioButton();
        SaveLogin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Limpiar = new javax.swing.JButton();
        SavePassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setText("Correo:");

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 0));
        jLabel5.setText("Nivel de acceso:");

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 0));
        jLabel6.setText("Mantenimiento de usuario.");

        SaveLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveLastNameActionPerformed(evt);
            }
        });

        GuardarUsu.setBackground(new java.awt.Color(204, 204, 0));
        GuardarUsu.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        GuardarUsu.setText("Guardar");
        GuardarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarUsuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Password:");

        Salida.setBackground(new java.awt.Color(204, 204, 0));
        Salida.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Salida.setText("Cancelar");
        Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("Nombre:");

        Estado.setBackground(new java.awt.Color(204, 204, 0));
        Estado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Estado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Estado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText("Apellido:");

        Acceso1.setBackground(new java.awt.Color(204, 204, 0));
        NivelesdeAcceso.add(Acceso1);
        Acceso1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Acceso1.setText("1");
        Acceso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Acceso1ActionPerformed(evt);
            }
        });

        Acceso0.setBackground(new java.awt.Color(204, 204, 0));
        NivelesdeAcceso.add(Acceso0);
        Acceso0.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Acceso0.setText("0");
        Acceso0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Acceso0ActionPerformed(evt);
            }
        });

        SaveLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambioDeEstado(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 0));
        jLabel7.setText("Login:");

        Limpiar.setBackground(new java.awt.Color(204, 204, 0));
        Limpiar.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SaveNombre)
                                    .addComponent(SaveLogin)
                                    .addComponent(SaveLastName)
                                    .addComponent(SaveEmail)
                                    .addComponent(SavePassword, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Acceso0)
                                .addGap(18, 18, 18)
                                .addComponent(Acceso1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(GuardarUsu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Limpiar)
                                .addGap(18, 18, 18)
                                .addComponent(Salida)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(SaveLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(SavePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(SaveNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SaveLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SaveEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Acceso1)
                    .addComponent(Acceso0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarUsu)
                    .addComponent(Limpiar)
                    .addComponent(Salida))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveLastNameActionPerformed

    private void SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaActionPerformed
        dispose();
    }//GEN-LAST:event_SalidaActionPerformed

    private void GuardarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarUsuActionPerformed
        ArchivadorUsuarios dato = new ArchivadorUsuarios();
        Usuarios person = new Usuarios();

        person.Login_Ususario = SaveLogin.getText();
        person.Nombre__Usuario = SaveNombre.getText();
        person.Apellido_Usuario = SaveLastName.getText();
        person.Correo_Usuario = SaveEmail.getText();
        person.Pass_Usuario = SavePassword.getText();

        if (Acceso0.isSelected()) {
            person.Nivel_Acceso = 0;
        } else {
            person.Nivel_Acceso = 1;
        }
        dato.GuardarDato(person.Login_Ususario, person.Nivel_Acceso, person.Nombre__Usuario, person.Apellido_Usuario, person.Correo_Usuario, person.Pass_Usuario);

        SaveLogin.setText("");
        SaveNombre.setText("");
        SaveLastName.setText("");
        SaveEmail.setText("");
        SavePassword.setText("");
        Estado.setText("");
    }//GEN-LAST:event_GuardarUsuActionPerformed

    private void CambioDeEstado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambioDeEstado
        String estado;
        String login = SaveLogin.getText();
        ArchivadorUsuarios buscar = new ArchivadorUsuarios();

        if (login == buscar.BuscarDato(login)) {
            Estado.setText("Modificar usuario existente.");

            SaveNombre.setText(buscar.LeerDatoEspecifico(2));
            SaveLastName.setText(buscar.LeerDatoEspecifico(3));
            SaveEmail.setText(buscar.LeerDatoEspecifico(4));
            SavePassword.setText(buscar.LeerDatoEspecifico(5));
        } else {
            Estado.setText("Crear usuario no existente.");

            SaveNombre.setText("");
            SaveLastName.setText("");
            SaveEmail.setText("");
            SavePassword.setText("");
        }
    }//GEN-LAST:event_CambioDeEstado

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        SaveLogin.setText("");
        SaveNombre.setText("");
        SaveLastName.setText("");
        SaveEmail.setText("");
        SavePassword.setText("");
        Estado.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    private void Acceso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Acceso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Acceso1ActionPerformed

    private void Acceso0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Acceso0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Acceso0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Acceso0;
    private javax.swing.JRadioButton Acceso1;
    private javax.swing.JLabel Estado;
    private javax.swing.JButton GuardarUsu;
    private javax.swing.JButton Limpiar;
    private javax.swing.ButtonGroup NivelesdeAcceso;
    private javax.swing.JButton Salida;
    private javax.swing.JTextField SaveEmail;
    private javax.swing.JTextField SaveLastName;
    private javax.swing.JTextField SaveLogin;
    private javax.swing.JTextField SaveNombre;
    private javax.swing.JPasswordField SavePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
