/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

/**
 *
 * @author Daniel
 */
public class MenuDeInteraccion extends javax.swing.JFrame {

    /**
     * Creates new form MenuDeInteraccion
     */
    public MenuDeInteraccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BarraDeOpciones = new javax.swing.JMenuBar();
        Mantenimiento = new javax.swing.JMenu();
        OpMantUsuario = new javax.swing.JMenuItem();
        OpMantEntrenador = new javax.swing.JMenuItem();
        OpMantLocalizacion = new javax.swing.JMenuItem();
        OpMantSalas = new javax.swing.JMenuItem();
        OpMantHorActividades = new javax.swing.JMenuItem();
        OpMantActividades = new javax.swing.JMenuItem();
        OpMantClientes = new javax.swing.JMenuItem();
        OpMantEstReservas = new javax.swing.JMenuItem();
        OpMantReservas = new javax.swing.JMenuItem();
        OpMantReservaAct = new javax.swing.JMenuItem();
        Movimientos = new javax.swing.JMenu();
        MovCuotas = new javax.swing.JMenuItem();
        Procesos = new javax.swing.JMenu();
        GenCobro = new javax.swing.JMenuItem();
        ResCobro = new javax.swing.JMenuItem();
        ActCuota = new javax.swing.JMenuItem();
        Consulta = new javax.swing.JMenu();
        ConUsuario = new javax.swing.JMenuItem();
        ConEntrenador = new javax.swing.JMenuItem();
        ConLocalizacion = new javax.swing.JMenuItem();
        ConSalas = new javax.swing.JMenuItem();
        ConActividades = new javax.swing.JMenuItem();
        ConHActividades = new javax.swing.JMenuItem();
        ConCobroFecha = new javax.swing.JMenuItem();
        ConCobroCliente = new javax.swing.JMenuItem();
        ConCuotaXFecha = new javax.swing.JMenuItem();
        ConCuotaXCliente = new javax.swing.JMenuItem();
        ConClientes = new javax.swing.JMenuItem();
        ConClienteBalPend = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(25, 23, 23));
        jPanel1.setForeground(new java.awt.Color(51, 51, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Gym.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel2)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        BarraDeOpciones.setBackground(new java.awt.Color(204, 204, 0));

        Mantenimiento.setText("Mantenimiento");

        OpMantUsuario.setText("Usuario");
        OpMantUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpMantUsuarioActionPerformed(evt);
            }
        });
        Mantenimiento.add(OpMantUsuario);

        OpMantEntrenador.setText("Entrenador");
        OpMantEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpMantEntrenadorActionPerformed(evt);
            }
        });
        Mantenimiento.add(OpMantEntrenador);

        OpMantLocalizacion.setText("Localizacion");
        OpMantLocalizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpMantLocalizacionActionPerformed(evt);
            }
        });
        Mantenimiento.add(OpMantLocalizacion);

        OpMantSalas.setText("Salas");
        OpMantSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpMantSalasActionPerformed(evt);
            }
        });
        Mantenimiento.add(OpMantSalas);

        OpMantHorActividades.setText("Horarios de actividades");
        OpMantHorActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpMantHorActividadesActionPerformed(evt);
            }
        });
        Mantenimiento.add(OpMantHorActividades);

        OpMantActividades.setText("Actividades");
        OpMantActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpMantActividadesActionPerformed(evt);
            }
        });
        Mantenimiento.add(OpMantActividades);

        OpMantClientes.setText("Clientes");
        OpMantClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpMantClientesActionPerformed(evt);
            }
        });
        Mantenimiento.add(OpMantClientes);

        OpMantEstReservas.setText("Estado Reservas");
        OpMantEstReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpMantEstReservasActionPerformed(evt);
            }
        });
        Mantenimiento.add(OpMantEstReservas);

        OpMantReservas.setText("Reservas");
        OpMantReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpMantReservasActionPerformed(evt);
            }
        });
        Mantenimiento.add(OpMantReservas);

        OpMantReservaAct.setText("Reserva actividades");
        OpMantReservaAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpMantReservaActActionPerformed(evt);
            }
        });
        Mantenimiento.add(OpMantReservaAct);

        BarraDeOpciones.add(Mantenimiento);

        Movimientos.setText("Movimientos");

        MovCuotas.setText("Cuotas");
        Movimientos.add(MovCuotas);

        BarraDeOpciones.add(Movimientos);

        Procesos.setText("Procesos");

        GenCobro.setText("Generar Cobro");
        Procesos.add(GenCobro);

        ResCobro.setText("Reservar Cobro");
        Procesos.add(ResCobro);

        ActCuota.setText("Actualizar Cuota");
        Procesos.add(ActCuota);

        BarraDeOpciones.add(Procesos);

        Consulta.setText("Consulta");

        ConUsuario.setText("De usuario");
        Consulta.add(ConUsuario);

        ConEntrenador.setText("De entrenador");
        Consulta.add(ConEntrenador);

        ConLocalizacion.setText("Localizacion");
        Consulta.add(ConLocalizacion);

        ConSalas.setText("Salas");
        Consulta.add(ConSalas);

        ConActividades.setText("Actividades");
        Consulta.add(ConActividades);

        ConHActividades.setText("Horas de actividades");
        Consulta.add(ConHActividades);

        ConCobroFecha.setText("Cobro por rango de fecha");
        Consulta.add(ConCobroFecha);

        ConCobroCliente.setText("Cobro por clientes");
        Consulta.add(ConCobroCliente);

        ConCuotaXFecha.setText("Cuota por fechas");
        Consulta.add(ConCuotaXFecha);

        ConCuotaXCliente.setText("Cuota por clientes");
        Consulta.add(ConCuotaXCliente);

        ConClientes.setText("Clientes");
        Consulta.add(ConClientes);

        ConClienteBalPend.setText("Clientes con balance pendiente");
        Consulta.add(ConClienteBalPend);

        BarraDeOpciones.add(Consulta);

        setJMenuBar(BarraDeOpciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Verificar nivel.
    public void comprobante(int nivel){
        if(nivel==0){
            System.out.println("[Usuario de nivel 0]");
        }else{
            System.out.println("[Usuario de nivel 1]");
        }
    }
    private void OpMantUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpMantUsuarioActionPerformed
        String[] args=null;
        MantUsuario.main(args);
    }//GEN-LAST:event_OpMantUsuarioActionPerformed

    private void OpMantEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpMantEntrenadorActionPerformed
        String[] args=null;
        MantEntrenador.main(args);
    }//GEN-LAST:event_OpMantEntrenadorActionPerformed

    private void OpMantLocalizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpMantLocalizacionActionPerformed
        String[] args = null;
        MantLocalizacion.main(args);
    }//GEN-LAST:event_OpMantLocalizacionActionPerformed

    private void OpMantSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpMantSalasActionPerformed
        String[] args = null;
        MantSalas.main(args);
    }//GEN-LAST:event_OpMantSalasActionPerformed

    private void OpMantHorActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpMantHorActividadesActionPerformed
        String[] args = null;
        MantHorActividades.main(args);
    }//GEN-LAST:event_OpMantHorActividadesActionPerformed

    private void OpMantActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpMantActividadesActionPerformed
        String[] args = null;
        MantActividades.main(args);
    }//GEN-LAST:event_OpMantActividadesActionPerformed

    private void OpMantClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpMantClientesActionPerformed
        String[] args = null;
        MantClientes.main(args);
    }//GEN-LAST:event_OpMantClientesActionPerformed

    private void OpMantEstReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpMantEstReservasActionPerformed
        String[] args = null;
        MantEstadoReservas.main(args);
    }//GEN-LAST:event_OpMantEstReservasActionPerformed

    private void OpMantReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpMantReservasActionPerformed
        String[] args = null;
        MantReservas.main(args);
    }//GEN-LAST:event_OpMantReservasActionPerformed

    private void OpMantReservaActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpMantReservaActActionPerformed
        String[] args = null;
        MantReservaAct.main(args);
    }//GEN-LAST:event_OpMantReservaActActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        MenuDeInteraccion seguro=new MenuDeInteraccion();
        //seguro.comprobante(1);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDeInteraccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDeInteraccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDeInteraccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDeInteraccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDeInteraccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ActCuota;
    private javax.swing.JMenuBar BarraDeOpciones;
    private javax.swing.JMenuItem ConActividades;
    private javax.swing.JMenuItem ConClienteBalPend;
    private javax.swing.JMenuItem ConClientes;
    private javax.swing.JMenuItem ConCobroCliente;
    private javax.swing.JMenuItem ConCobroFecha;
    private javax.swing.JMenuItem ConCuotaXCliente;
    private javax.swing.JMenuItem ConCuotaXFecha;
    private javax.swing.JMenuItem ConEntrenador;
    private javax.swing.JMenuItem ConHActividades;
    private javax.swing.JMenuItem ConLocalizacion;
    private javax.swing.JMenuItem ConSalas;
    private javax.swing.JMenuItem ConUsuario;
    private javax.swing.JMenu Consulta;
    private javax.swing.JMenuItem GenCobro;
    private javax.swing.JMenu Mantenimiento;
    private javax.swing.JMenuItem MovCuotas;
    private javax.swing.JMenu Movimientos;
    private javax.swing.JMenuItem OpMantActividades;
    private javax.swing.JMenuItem OpMantClientes;
    private javax.swing.JMenuItem OpMantEntrenador;
    private javax.swing.JMenuItem OpMantEstReservas;
    private javax.swing.JMenuItem OpMantHorActividades;
    private javax.swing.JMenuItem OpMantLocalizacion;
    private javax.swing.JMenuItem OpMantReservaAct;
    private javax.swing.JMenuItem OpMantReservas;
    private javax.swing.JMenuItem OpMantSalas;
    private javax.swing.JMenuItem OpMantUsuario;
    private javax.swing.JMenu Procesos;
    private javax.swing.JMenuItem ResCobro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
